Traceback (most recent call last):
  File "E:\dev\wPCC_pipeline\venv\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "E:\dev\wPCC_pipeline\venv\lib\site-packages\nbclient\client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "E:\dev\wPCC_pipeline\venv\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "E:\dev\wPCC_pipeline\venv\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Python37-64\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "E:\dev\wPCC_pipeline\venv\lib\site-packages\nbclient\client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "E:\dev\wPCC_pipeline\venv\lib\site-packages\nbclient\client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "E:\dev\wPCC_pipeline\venv\lib\site-packages\nbclient\client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np, pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from scipy.optimize import minimize
import scipy.stats as stats
import statsmodels.api as sm
from myst_nb import glue

import os
if os.name == 'nt':
    plt.style.use('book.mplstyle')  # Windows
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_25504/1887912568.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m,[0m [0mpandas[0m [1;32mas[0m [0mpd[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m [1;32mfrom[0m [0mmatplotlib[0m [1;32mimport[0m [0mpyplot[0m [1;32mas[0m [0mplt[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 3[1;33m [1;32mimport[0m [0mseaborn[0m [1;32mas[0m [0msns[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      4[0m [1;32mfrom[0m [0mscipy[0m[1;33m.[0m[0moptimize[0m [1;32mimport[0m [0mminimize[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;32mimport[0m [0mscipy[0m[1;33m.[0m[0mstats[0m [1;32mas[0m [0mstats[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'seaborn'
ModuleNotFoundError: No module named 'seaborn'

